name: cf DDNS Auto Update

on:
  schedule:
    - cron: '45 */1 * * *' 
  workflow_dispatch: 
  repository_dispatch: #允许外部触发,cf worker定时任务延迟在1分钟以内
    types: [dnscron]
jobs:
  update-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: |
          npm install playwright axios
          npx playwright install chromium --with-deps

      - name: Run Update Script
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          ISP: ${{ secrets.ISP }}
          RECORD_NAME: ${{ secrets.RECORD_NAME }}
          TARGET_URL: ${{ secrets.TARGET_URL }}
        run: node ud104162.js
